spring:
  #    devtools:
  #      restart:
  #        enabled: true  #设置开启热部署
  #  freemarker:
  #    cache: true      #页面不加载缓存，修改即时生效

  #redis
  #  redis:
  #    host: localhost
  #    port: 6379
  #数据源
  thymeleaf:
    #prefix: classpath:/templates
    suffix: .html
    mode: html5
    cache: false #开发时关闭缓存,不然没法看到实时页面
    encoding: utf-8

  profiles:
    active: dev
    # 数据库访问配置
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      # 连接池配置
      # 初始化大小，最小，最大
      initial-size: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      name: era
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      min-idle: 5


#服务器
server:
  port: 8081

  servlet:
    session:
      cookie:
        http-only: true
      tracking-modes: cookie

#mybatis配置
mybatis:
  type-aliases-package: com.example.shiro.mapper
  configLocation: classpath:/mybatis-config.xml



